short_thresh: 10
long_thresh: 30
num_robots: 3
goal_parameters:
    threshold: 0.5
    loiter_time: 5
robot_parameters:
    - start: [  0,  0, 0]
      goals: [
        [ 20,  5],
        [ 25,  0],
      ]
    - start: [  0,  10, 1]
      goals:  [
        [ 25, 0],
        [ 20, 5],
    ]
    - start: [  0,  -10, 1]
      goals:  [
        [ -25, 0]
    ]
slam_parameters:
    use_range: true
    short_range_history: 10
    sigma_initial: [
        [0.001, 0.0, 0.0],
        [0.0, 0.1, 0.0],
        [0.0, 0.0, 0.1],
    ]
    sigma_odom: [
        [0.0001, 0.0, 0.0],
        [0.0, 0.001, 0.0],
        [0.0, 0.0, 0.001]
    ]
    sigma_fake_odom: [
        [1, 0.0, 0.0],
        [0.0, 10, 0.0],
        [0.0, 0.0, 10]
    ]
    sigma_range: [
        [1e-6]
    ]
motion_parameters:
    disturbance: no_force
    sigma_initial: [
        [0.001, 0.0, 0.0],
        [0.0, 0.1, 0.0],
        [0.0, 0.0, 0.1],
    ]
    sigma_odom: [
        [0.0001, 0.0, 0.0],
        [0.0, 0.001, 0.0],
        [0.0, 0.0, 0.001]
    ]
    sigma_control: [
        [0.0001, 0.0, 0.0],
        [0.0, 0.001, 0.0],
        [0.0, 0.0, 0.001]
    ]
sensor_parameters:
    - delta: [0,  .1]
      orientation: 0
      fov: 360
    - delta: [0, -.1]
      orientation: 180
      fov: 360
    - delta: [-.1, 0]
      orientation: 0
      fov: 360
sensor_sigma: 0.01
