short_thresh: 2
long_thresh: 50
num_robots: 2
sigma_initial: [
    [0.001, 0.0, 0.0],
    [0.0, 0.1, 0.0],
    [0.0, 0.0, 0.1],
]
sigma_odom: [
    [0.001, 0.0, 0.0],
    [0.0, 0.01, 0.0],
    [0.0, 0.0, 0.01]
]
sigma_range: [
    [0.00001]
]
robot_parameters:
    - start: [  0,  5, 1]
      goal:  [ 10,  1]
    - start: [  0,  0, 0]
      goal:  [ 1, 10]
sensor_parameters:
    - delta: [0,  1]
      orientation: 0
      fov: 360
    - delta: [0, -1]
      orientation: 180
      fov: 360
    - delta: [-1, 0]
      orientation: 0
      fov: 360
sensor_sigma: 0.1
